// Generated automatically by nearley, version 2.16.0
// http://github.com/Hardmath123/nearley
function id(x) { return x[0]; }

const Pattern_Disjunction = ([Disjunction]) => ({ type: 'Pattern', Disjunction });


const Disjunction_Alternative = ([Alternative]) => ({ type: 'Disjunction', Alternatives: [Alternative] });
const Disjunction_Alternative_Disjunction = ([Alternative, _, Disjunction]) => ({ type: 'Disjunction', Alternatives: [Alternative, ...Disjunction.Alternatives] });


const Alternative_empty = () => ({ type: 'Alternative', Terms: [] });
const Alternative_Alternative_Term = ([Alternative, Term]) => {
  Alternative.Terms.push(Term);
  return Alternative;
};


const Term_Assertion = ([Assertion]) => ({ type: 'Term', subtype: 'Assertion', Assertion });
const Term_Atom = ([Atom]) => ({ type: 'Term', subtype: 'Atom', Atom });
const Term_Atom_Quantifier = ([Atom, Quantifier]) => ({ type: 'Term', subtype: 'AtomQuantifier', Atom, Quantifier });


const Assertion_nt = ([ch]) => ({ type: 'Assertion', subtype: ch });
const Assertion_Disjunction = ([ch, Disjunction]) => ({ type: 'Assertion', subtype: ch, Disjunction });


const QuantifierPrefix_nt = ([ch]) => ({ type: 'QuantifierPrefix', subtype: ch });
let Lexer = undefined;
let ParserRules = [
    {"name": "Pattern", "symbols": ["Disjunction"], "postprocess": Pattern_Disjunction},
    {"name": "Pattern_U", "symbols": ["Disjunction_U"], "postprocess": Pattern_Disjunction},
    {"name": "Pattern_N", "symbols": ["Disjunction_N"], "postprocess": Pattern_Disjunction},
    {"name": "Pattern_U_N", "symbols": ["Disjunction_U_N"], "postprocess": Pattern_Disjunction},
    {"name": "Disjunction", "symbols": ["Alternative"], "postprocess": Disjunction_Alternative},
    {"name": "Disjunction", "symbols": ["Alternative", {"literal":"|"}, "Disjunction"], "postprocess": Disjunction_Alternative_Disjunction},
    {"name": "Disjunction_U", "symbols": ["Alternative_U"], "postprocess": Disjunction_Alternative},
    {"name": "Disjunction_U", "symbols": ["Alternative_U", {"literal":"|"}, "Disjunction_U"], "postprocess": Disjunction_Alternative_Disjunction},
    {"name": "Disjunction_N", "symbols": ["Alternative_N"], "postprocess": Disjunction_Alternative},
    {"name": "Disjunction_N", "symbols": ["Alternative_N", {"literal":"|"}, "Disjunction_N"], "postprocess": Disjunction_Alternative_Disjunction},
    {"name": "Disjunction_U_N", "symbols": ["Alternative_U_N"], "postprocess": Disjunction_Alternative},
    {"name": "Disjunction_U_N", "symbols": ["Alternative_U_N", {"literal":"|"}, "Disjunction_U_N"], "postprocess": Disjunction_Alternative_Disjunction},
    {"name": "Alternative", "symbols": [], "postprocess": Alternative_empty},
    {"name": "Alternative", "symbols": ["Alternative", "Term"], "postprocess": Alternative_Alternative_Term},
    {"name": "Alternative_U", "symbols": [], "postprocess": Alternative_empty},
    {"name": "Alternative_U", "symbols": ["Alternative_U", "Term_U"], "postprocess": Alternative_Alternative_Term},
    {"name": "Alternative_N", "symbols": [], "postprocess": Alternative_empty},
    {"name": "Alternative_N", "symbols": ["Alternative_N", "Term_N"], "postprocess": Alternative_Alternative_Term},
    {"name": "Alternative_U_N", "symbols": [], "postprocess": Alternative_empty},
    {"name": "Alternative_U_N", "symbols": ["Alternative_U_N", "Term_U_N"], "postprocess": Alternative_Alternative_Term},
    {"name": "Term", "symbols": ["Assertion"], "postprocess": Term_Assertion},
    {"name": "Term", "symbols": ["Atom"], "postprocess": Term_Atom},
    {"name": "Term", "symbols": ["Atom", "Quantifier"], "postprocess": Term_Atom_Quantifier},
    {"name": "Term_U", "symbols": ["Assertion_U"], "postprocess": Term_Assertion},
    {"name": "Term_U", "symbols": ["Atom_U"], "postprocess": Term_Atom},
    {"name": "Term_U", "symbols": ["Atom_U", "Quantifier"], "postprocess": Term_Atom_Quantifier},
    {"name": "Term_N", "symbols": ["Assertion_N"], "postprocess": Term_Assertion},
    {"name": "Term_N", "symbols": ["Atom_N"], "postprocess": Term_Atom},
    {"name": "Term_N", "symbols": ["Atom_N", "Quantifier"], "postprocess": Term_Atom_Quantifier},
    {"name": "Term_U_N", "symbols": ["Assertion_U_N"], "postprocess": Term_Assertion},
    {"name": "Term_U_N", "symbols": ["Atom_U_N"], "postprocess": Term_Atom},
    {"name": "Term_U_N", "symbols": ["Atom_U_N", "Quantifier"], "postprocess": Term_Atom_Quantifier},
    {"name": "Assertion", "symbols": [{"literal":"^"}], "postprocess": Assertion_nt},
    {"name": "Assertion", "symbols": [{"literal":"$"}], "postprocess": Assertion_nt},
    {"name": "Assertion$string$1", "symbols": [{"literal":"\\"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion", "symbols": ["Assertion$string$1"], "postprocess": Assertion_nt},
    {"name": "Assertion$string$2", "symbols": [{"literal":"\\"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion", "symbols": ["Assertion$string$2"], "postprocess": Assertion_nt},
    {"name": "Assertion$string$3", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion", "symbols": ["Assertion$string$3", "Disjunction", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion$string$4", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion", "symbols": ["Assertion$string$4", "Disjunction", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion$string$5", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"<"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion", "symbols": ["Assertion$string$5", "Disjunction", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion$string$6", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"<"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion", "symbols": ["Assertion$string$6", "Disjunction", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion_U", "symbols": [{"literal":"^"}], "postprocess": Assertion_nt},
    {"name": "Assertion_U", "symbols": [{"literal":"$"}], "postprocess": Assertion_nt},
    {"name": "Assertion_U$string$1", "symbols": [{"literal":"\\"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_U", "symbols": ["Assertion_U$string$1"], "postprocess": Assertion_nt},
    {"name": "Assertion_U$string$2", "symbols": [{"literal":"\\"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_U", "symbols": ["Assertion_U$string$2"], "postprocess": Assertion_nt},
    {"name": "Assertion_U$string$3", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_U", "symbols": ["Assertion_U$string$3", "Disjunction_U", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion_U$string$4", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_U", "symbols": ["Assertion_U$string$4", "Disjunction_U", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion_U$string$5", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"<"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_U", "symbols": ["Assertion_U$string$5", "Disjunction_U", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion_U$string$6", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"<"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_U", "symbols": ["Assertion_U$string$6", "Disjunction_U", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion_N", "symbols": [{"literal":"^"}], "postprocess": Assertion_nt},
    {"name": "Assertion_N", "symbols": [{"literal":"$"}], "postprocess": Assertion_nt},
    {"name": "Assertion_N$string$1", "symbols": [{"literal":"\\"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_N", "symbols": ["Assertion_N$string$1"], "postprocess": Assertion_nt},
    {"name": "Assertion_N$string$2", "symbols": [{"literal":"\\"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_N", "symbols": ["Assertion_N$string$2"], "postprocess": Assertion_nt},
    {"name": "Assertion_N$string$3", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_N", "symbols": ["Assertion_N$string$3", "Disjunction_N", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion_N$string$4", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_N", "symbols": ["Assertion_N$string$4", "Disjunction_N", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion_N$string$5", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"<"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_N", "symbols": ["Assertion_N$string$5", "Disjunction_N", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion_N$string$6", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"<"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_N", "symbols": ["Assertion_N$string$6", "Disjunction_N", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion_U_N", "symbols": [{"literal":"^"}], "postprocess": Assertion_nt},
    {"name": "Assertion_U_N", "symbols": [{"literal":"$"}], "postprocess": Assertion_nt},
    {"name": "Assertion_U_N$string$1", "symbols": [{"literal":"\\"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_U_N", "symbols": ["Assertion_U_N$string$1"], "postprocess": Assertion_nt},
    {"name": "Assertion_U_N$string$2", "symbols": [{"literal":"\\"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_U_N", "symbols": ["Assertion_U_N$string$2"], "postprocess": Assertion_nt},
    {"name": "Assertion_U_N$string$3", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_U_N", "symbols": ["Assertion_U_N$string$3", "Disjunction_U_N", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion_U_N$string$4", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_U_N", "symbols": ["Assertion_U_N$string$4", "Disjunction_U_N", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion_U_N$string$5", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"<"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_U_N", "symbols": ["Assertion_U_N$string$5", "Disjunction_U_N", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Assertion_U_N$string$6", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":"<"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Assertion_U_N", "symbols": ["Assertion_U_N$string$6", "Disjunction_U_N", {"literal":")"}], "postprocess": Assertion_Disjunction},
    {"name": "Quantifier", "symbols": ["QuantifierPrefix"], "postprocess": ([QuantifierPrefix]) => ({ type: 'Quantifier', QuantifierPrefix, lazy: false })},
    {"name": "Quantifier", "symbols": ["QuantifierPrefix", {"literal":"?"}], "postprocess": ([QuantifierPrefix]) => ({ type: 'Quantifier', QuantifierPrefix, lazy: true })},
    {"name": "QuantifierPrefix", "symbols": [{"literal":"*"}], "postprocess": QuantifierPrefix_nt},
    {"name": "QuantifierPrefix", "symbols": [{"literal":"+"}], "postprocess": QuantifierPrefix_nt},
    {"name": "QuantifierPrefix", "symbols": [{"literal":"?"}], "postprocess": QuantifierPrefix_nt},
    {"name": "QuantifierPrefix", "symbols": [{"literal":"{"}, "DecimalDigits", {"literal":"}"}], "postprocess": ([_, DecimalDigits]) => ({ type: 'QuantifierPrefix', subtype: 'fixed', DecimalDigits })},
    {"name": "QuantifierPrefix$string$1", "symbols": [{"literal":","}, {"literal":"}"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QuantifierPrefix", "symbols": [{"literal":"{"}, "DecimalDigits", "QuantifierPrefix$string$1"], "postprocess": ([_, DecimalDigits]) => ({ type: 'QuantifierPrefix', subtype: 'start', DecimalDigits })},
    {"name": "QuantifierPrefix", "symbols": [{"literal":"{"}, "DecimalDigits", {"literal":","}, "DecimalDigits", {"literal":"}"}], "postprocess": ([_, DecimalDigits1, c, DecimalDigits2]) => ({ type: 'QuantifierPrefix', subtype: 'range', DecimalDigits1, DecimalDigits2 })},
    {"name": "Atom", "symbols": ["PatternCharacter"]},
    {"name": "Atom", "symbols": [{"literal":"."}]},
    {"name": "Atom", "symbols": [{"literal":"\\"}, "AtomEscape"]},
    {"name": "Atom", "symbols": ["CharacterClass"]},
    {"name": "Atom", "symbols": [{"literal":"("}, "GroupSpecifier", "Disjunction", {"literal":")"}], "postprocess": ([l, GroupSpecifier, Disjunction]) => ({ type: 'Atom', subtype: '(', GroupSpecifier, Disjunction })},
    {"name": "Atom$string$1", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Atom", "symbols": ["Atom$string$1", "Disjunction", {"literal":")"}]},
    {"name": "Atom_U", "symbols": ["PatternCharacter"]},
    {"name": "Atom_U", "symbols": [{"literal":"."}]},
    {"name": "Atom_U", "symbols": [{"literal":"\\"}, "AtomEscape_U"]},
    {"name": "Atom_U", "symbols": ["CharacterClass_U"]},
    {"name": "Atom_U", "symbols": [{"literal":"("}, "GroupSpecifier_U", "Disjunction_U", {"literal":")"}]},
    {"name": "Atom_U$string$1", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Atom_U", "symbols": ["Atom_U$string$1", "Disjunction_U", {"literal":")"}]},
    {"name": "Atom_N", "symbols": ["PatternCharacter"]},
    {"name": "Atom_N", "symbols": [{"literal":"."}]},
    {"name": "Atom_N", "symbols": [{"literal":"\\"}, "AtomEscape_N"]},
    {"name": "Atom_N", "symbols": ["CharacterClass"]},
    {"name": "Atom_N", "symbols": [{"literal":"("}, "GroupSpecifier", "Disjunction_N", {"literal":")"}]},
    {"name": "Atom_N$string$1", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Atom_N", "symbols": ["Atom_N$string$1", "Disjunction_N", {"literal":")"}]},
    {"name": "Atom_U_N", "symbols": ["PatternCharacter"]},
    {"name": "Atom_U_N", "symbols": [{"literal":"."}]},
    {"name": "Atom_U_N", "symbols": [{"literal":"\\"}, "AtomEscape_U_N"]},
    {"name": "Atom_U_N", "symbols": ["CharacterClass_U"]},
    {"name": "Atom_U_N", "symbols": [{"literal":"("}, "GroupSpecifier_U", "Disjunction_U_N", {"literal":")"}]},
    {"name": "Atom_U_N$string$1", "symbols": [{"literal":"("}, {"literal":"?"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Atom_U_N", "symbols": ["Atom_U_N$string$1", "Disjunction_U_N", {"literal":")"}]},
    {"name": "SyntaxCharacter", "symbols": [/[$^\\.*+?()[\]{}|]/]},
    {"name": "PatternCharacter", "symbols": ["SourceCharacter"], "postprocess": ([c], _, reject) => /[$^\\.*+?()[\]{}|]/.test(c) ? reject : { PatternCharacter: c }},
    {"name": "AtomEscape", "symbols": ["DecimalEscape"]},
    {"name": "AtomEscape", "symbols": ["CharacterClassEscape"]},
    {"name": "AtomEscape", "symbols": ["CharacterEscape"]},
    {"name": "AtomEscape_U", "symbols": ["DecimalEscape"]},
    {"name": "AtomEscape_U", "symbols": ["CharacterClassEscape_U"]},
    {"name": "AtomEscape_U", "symbols": ["CharacterEscape_U"]},
    {"name": "AtomEscape_N", "symbols": ["DecimalEscape"]},
    {"name": "AtomEscape_N", "symbols": ["CharacterClassEscape"]},
    {"name": "AtomEscape_N", "symbols": ["CharacterEscape"]},
    {"name": "AtomEscape_N", "symbols": [{"literal":"k"}, "GroupName"]},
    {"name": "AtomEscape_U_N", "symbols": ["DecimalEscape"]},
    {"name": "AtomEscape_U_N", "symbols": ["CharacterClassEscape_U"]},
    {"name": "AtomEscape_U_N", "symbols": ["CharacterEscape_U"]},
    {"name": "AtomEscape_U_N", "symbols": [{"literal":"k"}, "GroupName_U"]},
    {"name": "CharacterEscape", "symbols": ["ControlEscape"]},
    {"name": "CharacterEscape", "symbols": [{"literal":"c"}, "ControlLetter"]},
    {"name": "CharacterEscape", "symbols": [{"literal":"0"}]},
    {"name": "CharacterEscape", "symbols": ["HexEscapeSequence"]},
    {"name": "CharacterEscape", "symbols": ["RegExpUnicodeEscapeSequence"]},
    {"name": "CharacterEscape", "symbols": ["IdentityEscape"]},
    {"name": "CharacterEscape_U", "symbols": ["ControlEscape"]},
    {"name": "CharacterEscape_U", "symbols": [{"literal":"c"}, "ControlLetter"]},
    {"name": "CharacterEscape_U", "symbols": [{"literal":"0"}]},
    {"name": "CharacterEscape_U", "symbols": ["HexEscapeSequence"]},
    {"name": "CharacterEscape_U", "symbols": ["RegExpUnicodeEscapeSequence_U"]},
    {"name": "CharacterEscape_U", "symbols": ["IdentityEscape_U"]},
    {"name": "ControlEscape", "symbols": [/[fnrtv]/]},
    {"name": "ControlLetter", "symbols": [/[abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ]/]},
    {"name": "GroupSpecifier", "symbols": []},
    {"name": "GroupSpecifier", "symbols": [{"literal":"?"}, "GroupName"]},
    {"name": "GroupSpecifier_U", "symbols": []},
    {"name": "GroupSpecifier_U", "symbols": [{"literal":"?"}, "GroupName_U"]},
    {"name": "GroupName", "symbols": [{"literal":"<"}, "RegExpIdentifierName", {"literal":">"}]},
    {"name": "GroupName_U", "symbols": [{"literal":"<"}, "RegExpIdentifierName_U", {"literal":">"}]},
    {"name": "RegExpIdentifierName", "symbols": ["RegExpIdentifierStart"]},
    {"name": "RegExpIdentifierName", "symbols": ["RegExpIdentifierName", "RegExpIdentifierPart"]},
    {"name": "RegExpIdentifierName_U", "symbols": ["RegExpIdentifierStart_U"]},
    {"name": "RegExpIdentifierName_U", "symbols": ["RegExpIdentifierName_U", "RegExpIdentifierPart_U"]},
    {"name": "RegExpIdentifierStart", "symbols": [/[a-zA-Z]/]},
    {"name": "RegExpIdentifierStart", "symbols": [{"literal":"$"}]},
    {"name": "RegExpIdentifierStart", "symbols": [{"literal":"_"}]},
    {"name": "RegExpIdentifierStart", "symbols": [{"literal":"\\"}, "RegExpUnicodeEscapeSequence"]},
    {"name": "RegExpIdentifierStart_U", "symbols": [/[a-zA-Z]/]},
    {"name": "RegExpIdentifierStart_U", "symbols": [{"literal":"$"}]},
    {"name": "RegExpIdentifierStart_U", "symbols": [{"literal":"_"}]},
    {"name": "RegExpIdentifierStart_U", "symbols": [{"literal":"\\"}, "RegExpUnicodeEscapeSequence_U"]},
    {"name": "RegExpIdentifierPart", "symbols": [/[a-zA-Z0-9]/]},
    {"name": "RegExpIdentifierPart", "symbols": [{"literal":"$"}]},
    {"name": "RegExpIdentifierPart", "symbols": [{"literal":"\\"}, "RegExpUnicodeEscapeSequence"]},
    {"name": "RegExpIdentifierPart", "symbols": [/[\u200C]/]},
    {"name": "RegExpIdentifierPart", "symbols": [/[\u200D]/]},
    {"name": "RegExpIdentifierPart_U", "symbols": [/[a-zA-Z0-9]/]},
    {"name": "RegExpIdentifierPart_U", "symbols": [{"literal":"$"}]},
    {"name": "RegExpIdentifierPart_U", "symbols": [{"literal":"\\"}, "RegExpUnicodeEscapeSequence_U"]},
    {"name": "RegExpIdentifierPart_U", "symbols": [/[\u200C]/]},
    {"name": "RegExpIdentifierPart_U", "symbols": [/[\u200D]/]},
    {"name": "RegExpUnicodeEscapeSequence", "symbols": [{"literal":"u"}, "Hex4Digits"]},
    {"name": "RegExpUnicodeEscapeSequence_U$string$1", "symbols": [{"literal":"\\"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RegExpUnicodeEscapeSequence_U", "symbols": [{"literal":"u"}, "LeadSurrogate", "RegExpUnicodeEscapeSequence_U$string$1", "TrailSurrogate"]},
    {"name": "RegExpUnicodeEscapeSequence_U", "symbols": [{"literal":"u"}, "LeadSurrogate"]},
    {"name": "RegExpUnicodeEscapeSequence_U", "symbols": [{"literal":"u"}, "TrailSurrogate"]},
    {"name": "RegExpUnicodeEscapeSequence_U", "symbols": [{"literal":"u"}, "NonSurrogate"]},
    {"name": "RegExpUnicodeEscapeSequence_U$string$2", "symbols": [{"literal":"u"}, {"literal":"{"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RegExpUnicodeEscapeSequence_U", "symbols": ["RegExpUnicodeEscapeSequence_U$string$2", "CodePoint", {"literal":"}"}]},
    {"name": "LeadSurrogate", "symbols": ["Hex4Digits"]},
    {"name": "TrailSurrogate", "symbols": ["Hex4Digits"]},
    {"name": "NonSurrogate", "symbols": ["Hex4Digits"]},
    {"name": "IdentityEscape", "symbols": ["SourceCharacter"]},
    {"name": "IdentityEscape_U", "symbols": ["SyntaxCharacter"]},
    {"name": "IdentityEscape_U", "symbols": [{"literal":"/"}]},
    {"name": "DecimalEscape", "symbols": ["NonZeroDigit"]},
    {"name": "DecimalEscape", "symbols": ["NonZeroDigit", "DecimalDigits"]},
    {"name": "CharacterClassEscape", "symbols": [{"literal":"d"}]},
    {"name": "CharacterClassEscape", "symbols": [{"literal":"D"}]},
    {"name": "CharacterClassEscape", "symbols": [{"literal":"s"}]},
    {"name": "CharacterClassEscape", "symbols": [{"literal":"S"}]},
    {"name": "CharacterClassEscape", "symbols": [{"literal":"w"}]},
    {"name": "CharacterClassEscape", "symbols": [{"literal":"W"}]},
    {"name": "CharacterClassEscape_U", "symbols": [{"literal":"d"}]},
    {"name": "CharacterClassEscape_U", "symbols": [{"literal":"D"}]},
    {"name": "CharacterClassEscape_U", "symbols": [{"literal":"s"}]},
    {"name": "CharacterClassEscape_U", "symbols": [{"literal":"S"}]},
    {"name": "CharacterClassEscape_U", "symbols": [{"literal":"w"}]},
    {"name": "CharacterClassEscape_U", "symbols": [{"literal":"W"}]},
    {"name": "CharacterClassEscape_U$string$1", "symbols": [{"literal":"p"}, {"literal":"{"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CharacterClassEscape_U", "symbols": ["CharacterClassEscape_U$string$1", "UnicodePropertyValueExpression", {"literal":"}"}]},
    {"name": "CharacterClassEscape_U$string$2", "symbols": [{"literal":"P"}, {"literal":"{"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CharacterClassEscape_U", "symbols": ["CharacterClassEscape_U$string$2", "UnicodePropertyValueExpression", {"literal":"}"}]},
    {"name": "UnicodePropertyValueExpression", "symbols": ["UnicodePropertyName", {"literal":"="}, "UnicodePropertyValue"]},
    {"name": "UnicodePropertyValueExpression", "symbols": ["LoneUnicodePropertyNameOrValue"]},
    {"name": "UnicodePropertyName", "symbols": ["UnicodePropertyNameCharacters"]},
    {"name": "UnicodePropertyNameCharacters", "symbols": ["UnicodePropertyNameCharacter"]},
    {"name": "UnicodePropertyNameCharacters", "symbols": ["UnicodePropertyNameCharacter", "UnicodePropertyNameCharacters"]},
    {"name": "UnicodePropertyValue", "symbols": ["UnicodePropertyValueCharacters"]},
    {"name": "LoneUnicodePropertyNameOrValue", "symbols": ["UnicodePropertyValueCharacters"]},
    {"name": "UnicodePropertyValueCharacters", "symbols": ["UnicodePropertyValueCharacter"]},
    {"name": "UnicodePropertyValueCharacters", "symbols": ["UnicodePropertyValueCharacter", "UnicodePropertyValueCharacters"]},
    {"name": "UnicodePropertyValueCharacter", "symbols": ["UnicodePropertyNameCharacter"]},
    {"name": "UnicodePropertyValueCharacter", "symbols": [/[0-9]/]},
    {"name": "UnicodePropertyNameCharacter", "symbols": ["ControlLetter"]},
    {"name": "UnicodePropertyNameCharacter", "symbols": [{"literal":"_"}]},
    {"name": "CharacterClass", "symbols": [{"literal":"["}, "ClassRanges", {"literal":"]"}]},
    {"name": "CharacterClass$string$1", "symbols": [{"literal":"["}, {"literal":"^"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CharacterClass", "symbols": ["CharacterClass$string$1", "ClassRanges", {"literal":"]"}]},
    {"name": "CharacterClass_U", "symbols": [{"literal":"["}, "ClassRanges_U", {"literal":"]"}]},
    {"name": "CharacterClass_U$string$1", "symbols": [{"literal":"["}, {"literal":"^"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CharacterClass_U", "symbols": ["CharacterClass_U$string$1", "ClassRanges_U", {"literal":"]"}]},
    {"name": "ClassRanges", "symbols": []},
    {"name": "ClassRanges", "symbols": ["NonemptyClassRanges"]},
    {"name": "ClassRanges_U", "symbols": []},
    {"name": "ClassRanges_U", "symbols": ["NonemptyClassRanges_U"]},
    {"name": "NonemptyClassRanges", "symbols": ["ClassAtom"]},
    {"name": "NonemptyClassRanges", "symbols": ["ClassAtom", "NonemptyClassRangesNoDash"]},
    {"name": "NonemptyClassRanges", "symbols": ["ClassAtom", {"literal":"-"}, "ClassAtom", "ClassRanges"]},
    {"name": "NonemptyClassRanges_U", "symbols": ["ClassAtom_U"]},
    {"name": "NonemptyClassRanges_U", "symbols": ["ClassAtom_U", "NonemptyClassRangesNoDash_U"]},
    {"name": "NonemptyClassRanges_U", "symbols": ["ClassAtom_U", {"literal":"-"}, "ClassAtom_U", "ClassRanges_U"]},
    {"name": "NonemptyClassRangesNoDash", "symbols": ["ClassAtom"]},
    {"name": "NonemptyClassRangesNoDash", "symbols": ["ClassAtomNoDash", "NonemptyClassRangesNoDash"]},
    {"name": "NonemptyClassRangesNoDash", "symbols": ["ClassAtomNoDash", {"literal":"-"}, "ClassAtom", "ClassRanges"]},
    {"name": "NonemptyClassRangesNoDash_U", "symbols": ["ClassAtom_U"]},
    {"name": "NonemptyClassRangesNoDash_U", "symbols": ["ClassAtomNoDash_U", "NonemptyClassRangesNoDash_U"]},
    {"name": "NonemptyClassRangesNoDash_U", "symbols": ["ClassAtomNoDash_U", {"literal":"-"}, "ClassAtom_U", "ClassRanges_U"]},
    {"name": "ClassAtom", "symbols": [{"literal":"-"}]},
    {"name": "ClassAtom", "symbols": ["ClassAtomNoDash"]},
    {"name": "ClassAtom_U", "symbols": [{"literal":"-"}]},
    {"name": "ClassAtom_U", "symbols": ["ClassAtomNoDash_U"]},
    {"name": "ClassAtomNoDash", "symbols": ["SourceCharacter"], "postprocess": ([c], _, reject) => /[\\\]-]/.test(c) ? reject : c},
    {"name": "ClassAtomNoDash", "symbols": [{"literal":"\\"}, "ClassEscape"]},
    {"name": "ClassAtomNoDash_U", "symbols": ["SourceCharacter"], "postprocess": ([c], _, reject) => /[\\\]-]/.test(c) ? reject : c},
    {"name": "ClassAtomNoDash_U", "symbols": [{"literal":"\\"}, "ClassEscape_U"]},
    {"name": "ClassEscape", "symbols": [{"literal":"b"}]},
    {"name": "ClassEscape", "symbols": ["CharacterClassEscape"]},
    {"name": "ClassEscape", "symbols": ["CharacterEscape"]},
    {"name": "ClassEscape_U", "symbols": [{"literal":"b"}]},
    {"name": "ClassEscape_U", "symbols": [{"literal":"-"}]},
    {"name": "ClassEscape_U", "symbols": ["CharacterClassEscape_U"]},
    {"name": "ClassEscape_U", "symbols": ["CharacterEscape_U"]},
    {"name": "DecimalDigits", "symbols": ["DecimalDigit"]},
    {"name": "DecimalDigits", "symbols": ["DecimalDigits", "DecimalDigit"]},
    {"name": "DecimalDigit", "symbols": [/[0-9]/]},
    {"name": "HexEscapeSequence", "symbols": [{"literal":"x"}, "HexDigit", "HexDigit"]},
    {"name": "Hex4Digits", "symbols": ["HexDigit", "HexDigit", "HexDigit", "HexDigit"]},
    {"name": "HexDigit", "symbols": [/[0-9a-fA-F]/]},
    {"name": "CodePoint", "symbols": ["HexDigits"]},
    {"name": "HexDigits", "symbols": ["HexDigit"]},
    {"name": "HexDigits", "symbols": ["HexDigits", "HexDigit"]},
    {"name": "NonZeroDigit", "symbols": [/[1-9]/]},
    {"name": "SourceCharacter", "symbols": [/./], "postprocess": id}
];
let ParserStart = "Pattern";
export default { Lexer, ParserRules, ParserStart };
